export const errorMessages = {
  USER_ALREADY_EXISTS: 'error.userAlreadyExists',
  INCORRECT_CREDENTIALS: 'error.incorrectCredentials',
  USER_NOT_FOUND: 'error.userNotFound',
  USER_ACCOUNT_INACTIVE: 'error.userAccountInactive',
  USER_ACCOUNT_DISABLED: 'error.userAccountDisabled',
  INVALID_PASSWORD: 'error.invalidPassword',
  USER_IS_NOT_AUTHOR: 'error: User is not author',
  INVALID_SMS_CODE: 'error.invalidSMSCode',
  TREE_TYPE_NOT_EXIST: 'error: Tree type does not exist',
  TREE_NOT_EXIST: 'error: Tree does not exist',
  NOT_EXIST: 'error.notExist',
  TOKEN_EXPIRED: 'error.tokenExpired',
  WRONG_EMAIL: 'error.wrongEmail',
  INCORRECT_ARRAY: 'error.order request must be an array',
  EMPTY_ARRAY: 'error.empty array',
  INCORRECT_REQUEST: 'error.Bad Request',
  TOKEN_NOT_EXIST: 'error.Token not exist',
  SLOT_LIMIT_EXHAUSTED: 'error The slot limit has been exhausted',
};
